# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Run-Test-Configuration:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: TW_Test
        uses: tingweichoo/testproj004@twtest
        with:
          dryRun: true
          serverURL: https://edge.dai.webperfdev.com/
          testConfigID: 307fee3e-9d6b-43e6-b31e-f1d379f27cdf
          clientID: client:dai:agent:integration
          clientSecret: c38ce33d-5644-4198-b28f-9cf3d9ac05e4
          testResultPath: testproj005/TestResult

